package core

type SortType string

const (
	SORT_ID                 SortType = "ID"
	SORT_ID_DESC            SortType = "ID_DESC"
	SORT_TITLE_ROMAJI       SortType = "TITLE_ROMAJI"
	SORT_TITLE_ROMAJI_DESC  SortType = "TITLE_ROMAJI_DESC"
	SORT_TITLE_ENGLISH      SortType = "TITLE_ENGLISH"
	SORT_TITLE_ENGLISH_DESC SortType = "TITLE_ENGLISH_DESC"
	SORT_TITLE_NATIVE       SortType = "TITLE_NATIVE"
	SORT_TITLE_NATIVE_DESC  SortType = "TITLE_NATIVE_DESC"
	SORT_TYPE               SortType = "TYPE"
	SORT_TYPE_DESC          SortType = "TYPE_DESC"
	SORT_FORMAT             SortType = "FORMAT"
	SORT_FORMAT_DESC        SortType = "FORMAT_DESC"
	SORT_START_DATE         SortType = "START_DATE"
	SORT_START_DATE_DESC    SortType = "START_DATE_DESC"
	SORT_END_DATE           SortType = "END_DATE"
	SORT_END_DATE_DESC      SortType = "END_DATE_DESC"
	SORT_SCORE              SortType = "SCORE"
	SORT_SCORE_DESC         SortType = "SCORE_DESC"
	SORT_POPULARITY         SortType = "POPULARITY"
	SORT_POPULARITY_DESC    SortType = "POPULARITY_DESC"
	SORT_TRENDING           SortType = "TRENDING"
	SORT_TRENDING_DESC      SortType = "TRENDING_DESC"
	SORT_EPISODES           SortType = "EPISODES"
	SORT_EPISODES_DESC      SortType = "EPISODES_DESC"
	SORT_DURATION           SortType = "DURATION"
	SORT_DURATION_DESC      SortType = "DURATION_DESC"
	SORT_STATUS             SortType = "STATUS"
	SORT_STATUS_DESC        SortType = "STATUS_DESC"
	SORT_CHAPTERS           SortType = "CHAPTERS"
	SORT_CHAPTERS_DESC      SortType = "CHAPTERS_DESC"
	SORT_VOLUMES            SortType = "VOLUMES"
	SORT_VOLUMES_DESC       SortType = "VOLUMES_DESC"
	SORT_UPDATED_AT         SortType = "UPDATED_AT"
	SORT_UPDATED_AT_DESC    SortType = "UPDATED_AT_DESC"
	SORT_SEARCH_MATCH       SortType = "SEARCH_MATCH"
	SORT_FAVOURITES         SortType = "FAVOURITES"
	SORT_FAVOURITES_DESC    SortType = "FAVOURITES_DESC"
)

var SortTypes = map[SortType]string{
	SORT_ID:                 "ID",
	SORT_ID_DESC:            "ID_DESC",
	SORT_TITLE_ROMAJI:       "TITLE_ROMAJI",
	SORT_TITLE_ROMAJI_DESC:  "TITLE_ROMAJI_DESC",
	SORT_TITLE_ENGLISH:      "TITLE_ENGLISH",
	SORT_TITLE_ENGLISH_DESC: "TITLE_ENGLISH_DESC",
	SORT_TITLE_NATIVE:       "TITLE_NATIVE",
	SORT_TITLE_NATIVE_DESC:  "TITLE_NATIVE_DESC",
	SORT_TYPE:               "TYPE",
	SORT_TYPE_DESC:          "TYPE_DESC",
	SORT_FORMAT:             "FORMAT",
	SORT_FORMAT_DESC:        "FORMAT_DESC",
	SORT_START_DATE:         "START_DATE",
	SORT_START_DATE_DESC:    "START_DATE_DESC",
	SORT_END_DATE:           "END_DATE",
	SORT_END_DATE_DESC:      "END_DATE_DESC",
	SORT_SCORE:              "SCORE",
	SORT_SCORE_DESC:         "SCORE_DESC",
	SORT_POPULARITY:         "POPULARITY",
	SORT_POPULARITY_DESC:    "POPULARITY_DESC",
	SORT_TRENDING:           "TRENDING",
	SORT_TRENDING_DESC:      "TRENDING_DESC",
	SORT_EPISODES:           "EPISODES",
	SORT_EPISODES_DESC:      "EPISODES_DESC",
	SORT_DURATION:           "DURATION",
	SORT_DURATION_DESC:      "DURATION_DESC",
	SORT_STATUS:             "STATUS",
	SORT_STATUS_DESC:        "STATUS_DESC",
	SORT_CHAPTERS:           "CHAPTERS",
	SORT_CHAPTERS_DESC:      "CHAPTERS_DESC",
	SORT_VOLUMES:            "VOLUMES",
	SORT_VOLUMES_DESC:       "VOLUMES_DESC",
	SORT_UPDATED_AT:         "UPDATED_AT",
	SORT_UPDATED_AT_DESC:    "UPDATED_AT_DESC",
	SORT_SEARCH_MATCH:       "SEARCH_MATCH",
	SORT_FAVOURITES:         "FAVOURITES",
	SORT_FAVOURITES_DESC:    "FAVOURITES_DESC",
}
